# 4. Basic Array Operations and Broadcasting

In [ ]:
import numpy as np

Let us start with the simplest case: Performing mathematical operations between a NumPy array and a scalar is straight-forward.

In [ ]:
arr = np.array([[1., 2.], [3., 4.]])
print(arr)
print(arr * 2)

Here are some additional examples with more operations.

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

print(f"Original:\n {arr}")
print(f"Multiply by 2:\n {2.0 * arr}") # Multiply all values by 2
print(f"Divide by 10:\n {arr / 10.0}") # Divide all values by 10
print(f"Subtract 3:\n {arr - 3.0}")    # Subtract 3 from all values in arr
print(f"Add 4:\n {arr + 4.0}")         # Add 4 to all values in arr
print(f"Square:\n {arr ** 2}")         # Square all values in arr

If two NumPy arrays are of the **same shape**, we can just as easily perform element-wise operations as follows:

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[2, 1,-1], [3,.5, 2]])

print(f"arr1 =\n{arr1}")
print(f"arr2 =\n{arr2}")

print(f"arr1 + arr2 =\n{arr1 + arr2}")  # Element-wise addition
print(f"arr1 - arr2 =\n{arr1 - arr2}")  # Element-wise subtraction
print(f"arr1 * arr2 =\n{arr1 * arr2}")  # Element-wise multiplication
print(f"arr1 / arr2 =\n{arr1 / arr2}")  # Element-wise division
print(f"arr1 ** arr2 =\n{arr1 ** arr2}") # Element-wise exponentiation

Broadcasting allows NumPy to work with arrays of **different shapes** when performing arithmetic operations. The smaller array is "broadcast" across the larger array so that they have compatible shapes. This makes many operations much more efficient.

**Broadcasting Rules**
- Arrays have compatible shapes if the shapes are equal or one of them is 1 (in some dimension).
- If the arrays do not have the same number of dimensions, prepend the shape of the smaller array with ones until they have the same number of dimensions.
- If any dimension does not match and is not 1, then broadcasting will not work.

Operations involving a NumPy array and a scalar is a special case of broadcasting where the scalar (which we can think of as a NumPy array of shape `(1,)`) is broadcast to the same shape as the NumPy array.

Here is a more interesting example: If you have a 1D array and a 2D array where the 1D array's shape is compatible with the trailing dimensions of the 2D array, broadcasting will occur.

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

result = arr_2d + arr_1d # This will broadcast arr_1d into [[10, 20, 30], [10, 20, 30]] and then do addition element-wise!

print(result)

Here is another example of broadcasting where we want to multiply the first row of `arr_2d` by $1$ and the second row by $2$.

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([1, 2])

# Reshape arr_1d to (2, 1) to make it compatible
arr_1d = arr_1d.reshape(2, 1)

result = arr_2d * arr_1d
print(result)

When broadcasting is not possible, NumPy will raise an error. You will probably encounter this type of error message many times, so here is an example to help you get to know eachother.

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3, 4])

try:
    result = arr1 + arr2
except ValueError as e:
    print(f"Error: {e}")

**Summary:** Broadcasting makes it easy to perform operations on arrays of different shapes without having to manually resize them. By following the broadcasting rules, NumPy automatically handles the necessary shape transformations to enable efficient computation.

## Exercises

### 1. Adding Scalars to Arrays

Create a 1D array `arr` with values `[1, 2, 3, 4, 5]`. Add a scalar value `10` to `arr` using broadcasting and print the result.

The output should be `[11 12 13 14 15]`.

In [ ]:
# Your code here
arr = ...

### 2. Multiply 1D Arrays of Same Shape

Create two 1D arrays `arr1` with values `[1, 2, 3]` and `arr2` with values `[10, 20, 30]`. Multiply `arr1` and `arr2` element-wise and print the result.

The output should be `[10 40 90]`.

In [ ]:
# Your code here
arr1 = ...
arr2 = ...

### 3. Broadcasting with Different Shapes

Create a 2D array `arr1` with values `[[1, 2, 3], [4, 5, 6]]` and a 1D array `arr2` with values `[1, 2, 3]`. Add `arr1` and `arr2` and print the result. Try to understand how `arr2` was broadcasted by NumPy.

The output should be
```
[[2 4 6]
 [5 7 9]]
 ```

In [ ]:
# Your code here
arr1 = ...
arr2 = ...

### 4. Broadcasting with Different Dimensions

Create a 3D array `arr1` with shape `(2, 2, 3)` containing values from 1 to 12 (use `np.arange()` and `arr.reshape()`) and a 1D array `arr2` with values `[1, 2, 3]`. Add `arr1` and `arr2` and print the result. Try to understand how `arr2` was broadcasted by NumPy before the addition took place.

The output should be
```
[[[ 2  4  6]
  [ 5  7  9]]

 [[ 8 10 12]
  [11 13 15]]]
  ```

In [ ]:
# Your code here
arr1 = ...
arr2 = ...

### 5. Reshaping for Broadcasting

Create a 2D array `arr1` with shape `(3, 4)` containing values from 0 to 11 and a 1D array `arr2` with values `[1, 2, 3]`. Reshape `arr2` to be compatible with `arr1` and then add them together. Print the result and try to understand what is going on.

The output should be
```
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]
 ```

In [ ]:
# Your code here
arr1 = ...
arr2 = ...

### 6. Broadcasting with Higher Dimensions

Create a 3D array `arr1` with shape `(2, 3, 4)` containing values from 0 to 23 and a 1D array `arr2` with values `[1, 2, 3, 4]`. Add `arr1` and `arr2` and print the result. How did NumPy broadcast `arr2`?

The output should be
```
[[[ 1  3  5  7]
  [ 5  7  9 11]
  [ 9 11 13 15]]

 [[13 15 17 19]
  [17 19 21 23]
  [21 23 25 27]]]
  ```

In [ ]:
# Your code here
arr1 = ...
arr2 = ...